(define (plan get-ark-solution)
  (:problem get-ark)
  (:steps (travel indiana usa tanis)
          (excavate indiana ark tanis)
          (travel indiana tanis usa)
          (take nazis ark indiana usa)
          (non-executed (give indiana ark army usa))
          (open-ark nazis)
          (take army ark nazis usa)))